# Introduction to Julia
## Applications to Systems Biology

### Michael P.H. Stumpf

This notebook lays out the basics of Julia for scientific programming in systems biology.


## Variables and Basic Types in Julia

Julia is very expressive and in addition to the standard types known from other languages, ```Int, Float```, ```Bool``` and ```String``` it offers a great variety of other, more specialized types. *Typing*, as we will show later is an important element in helping *Julia* to be so fast.

For example we have

In [42]:
x1=4;x2=4.0;x3="four";x4 =true;x5=sin(x1)
println(typeof(x1))
println(typeof(x2))
println(typeof(x3))
println(typeof(x4))
println(typeof(x5))

Int64
Float64
String
Bool
Float64


The ```64``` after ```Int``` and ```Float``` denote the precission/memory associated with each variable. 

```String``` in turn, denotes the set of characters that can be associated with a given ```String```. _Julia_ has the ability to represent _Unicode_ natively.  

A single character is stored as a ```Char```

In [4]:
typeof(x3[1])

Char

Here we have started to use vector notation: each letter/character in a string can be accessed through its position in the string: in the above example, 

In [15]:
x3[1]

'f': ASCII/Unicode U+0066 (category Ll: Letter, lowercase)

Julia gives us many other options to define types of variables. Some of these are

In [6]:
r1=3//4; r2 = 2+3im; r3=2.0+pi*im
println(typeof(r1))
println(typeof(r2))
println(typeof(r3))

Rational{Int64}
Complex{Int64}
Complex{Float64}


Here we have used ```pi``` to denote $\pi$, which is build into _Julia_ like some other constants.

Explicit *typing* is one of the strengths of _Julia_: it allows for efficient code, as each variable can be allocated a precise amount of memory, which in turn allows for very efficient processing of the resulting machine code. Many languages forgo explicit typing, which means that they are more flexible and appear more userfriendly. _R_, _Python_ and _Matlab_ are popular examples that are used in scientific computing; while they assign types to variables as well, they do so in a dynamic way, where the interpreted typically has to infer the nature of a variable at execution time. This, however, leads almost inevitably to slower execution times.

In _Julia_ the nature of a variable is inferred at compile time, but we can help in this, by forcing certain types onto variables.

We will revisit types later on, but here it suffices to say that _Julia_ also allows us to define our own types and we will encounter a host of relevant special types, such as those referring to array, matrices, sparse matrices and graphs, later on.

## Vectors & Matrices

We typically want to work on large sets of variables and combine many of them in convenient formats.

In [7]:
a1 = [3.2,3.1,3]

3-element Array{Float64,1}:
 3.2
 3.1
 3.0

In [8]:
a2 = [3.2 3.1 3]

1×3 Array{Float64,2}:
 3.2  3.1  3.0

```a1``` is an array that represents a column vector, whereas ```a2``` would represent a row vector. 

Applying a function on the elements of such vectors is done by e.g. ```sin.(x)```, which applies the function ```sin``` component-wise and returns the output in the same format as the input.

In [12]:
sin.(a1)

3-element Array{Float64,1}:
 -0.0583741
  0.0415807
  0.14112  

In [10]:
sin.(a2)

1×3 Array{Float64,2}:
 -0.0583741  0.0415807  0.14112

Note that the row vector is already represented as a 2d Array or matrix; we can see this by asking for the dimension of the two vectors using ```ndims```:

In [13]:
ndims(a1)

1

In [14]:
ndims(a2)

2

_Indexing_, however, works similarly for both arrays:

In [25]:
println(a1[1])
println(a2[1])
println(a1[2])
println(a2[2])

3.2
3.2
3.1
3.1


Matrices are two-dimensional arrays and can be defined flexibly. We can specify the entries of the matrix explicitly,

In [1]:
amat = [ 1.0 2.0 3.0; 1.5 2.5 3.5]

2×3 Array{Float64,2}:
 1.0  2.0  3.0
 1.5  2.5  3.5

or use one of the many generators of matrices that _Julia_ offers. We can, for example, construct a $3\times4$ matrix containing onley "1"s

In [2]:
ones(4,3)

4×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

or generate a matrix containing $6\times 6$ random values drawn from the unit interval, i.e. $r_{ij}\in[0,1]$ for $1\le i,j \le 6$, 

In [3]:
rmat=rand(6,6)

6×6 Array{Float64,2}:
 0.371491   0.854054   0.470268  0.358902  0.275471  0.829826
 0.0236102  0.0585716  0.908118  0.647096  0.707748  0.798248
 0.83421    0.828837   0.342746  0.74896   0.719952  0.285807
 0.686808   0.107792   0.285756  0.735086  0.669953  0.483925
 0.367296   0.569715   0.605346  0.959884  0.835092  0.96003 
 0.593361   0.622308   0.369423  0.464087  0.545643  0.824879

### Matrix Arithmetic

_Julia_ has inherited much of _Matlab_'s matrix prowess. We can calculate the eigen-systems of a matrix (here we use ```rmat``` to illustrate the methods),

In [4]:
eig(rmat)

(Complex{Float64}[3.4655+0.0im, -0.485065+0.169079im, -0.485065-0.169079im, 0.250845+0.280479im, 0.250845-0.280479im, 0.170807+0.0im], Complex{Float64}[0.363338+0.0im -0.372228-0.201393im … 0.492392-0.0im -0.412852+0.0im; 0.382196+0.0im 0.637703+0.0im … -0.177822-0.284911im 0.0648972+0.0im; … ; 0.505034+0.0im -0.119838-0.20059im … -0.398973-0.136566im 0.673662+0.0im; 0.397718+0.0im -0.0849113+0.0662321im … 0.304052+0.206814im 0.204246+0.0im])

which yields a set of eigenvalues and eigenvectors. The eigenvalues are a mixture of real and pairs of complex conjugate numbers. Eigenvectors are real, but stored as complex values.

To process this further we can make use of _Julia_'s ```ans``` variable, which is the output of the last computation:

In [5]:
esystem=ans;

This we can now investiage further using ```typeof```

In [6]:
typeof(esystem)

Tuple{Array{Complex{Float64},1},Array{Complex{Float64},2}}

This array contains as the first element a vector of the eigenvalues (ordered by the size of the real part,

In [7]:
esystem[1]

6-element Array{Complex{Float64},1}:
    3.4655+0.0im     
 -0.485065+0.169079im
 -0.485065-0.169079im
  0.250845+0.280479im
  0.250845-0.280479im
  0.170807+0.0im     

and in its second element it has the set of eigenvectors,

In [8]:
esystem[2]

6×6 Array{Complex{Float64},2}:
 0.363338+0.0im   -0.372228-0.201393im   …  -0.412852+0.0im
 0.382196+0.0im    0.637703+0.0im           0.0648972+0.0im
  0.43441+0.0im   -0.433996+0.0596231im     -0.532417+0.0im
 0.346354+0.0im    0.322711+0.227987im      -0.215259+0.0im
 0.505034+0.0im   -0.119838-0.20059im        0.673662+0.0im
 0.397718+0.0im  -0.0849113+0.0662321im  …   0.204246+0.0im

These can now be processed further if so desired.

But there are also many other operations, that are natively implemented in _Julia_, e.g. transpose and determinant

In [9]:
transpose(rmat)

6×6 Array{Float64,2}:
 0.371491  0.0236102  0.83421   0.686808  0.367296  0.593361
 0.854054  0.0585716  0.828837  0.107792  0.569715  0.622308
 0.470268  0.908118   0.342746  0.285756  0.605346  0.369423
 0.358902  0.647096   0.74896   0.735086  0.959884  0.464087
 0.275471  0.707748   0.719952  0.669953  0.835092  0.545643
 0.829826  0.798248   0.285807  0.483925  0.96003   0.824879

In [10]:
det(rmat)

0.022116208895895634

and all standard examples from matrix algebra are defined and work as expected. Matrix multiplication, for example works as expected, e.g. with a new matrix ```bmat```

In [11]:
bmat = [ 1.5 2.7; 2.5 3.5; 3.5 3.7]

3×2 Array{Float64,2}:
 1.5  2.7
 2.5  3.5
 3.5  3.7

we obtain for the two possible matrix producs

In [12]:
amat*bmat

2×2 Array{Float64,2}:
 17.0   20.8 
 20.75  25.75

In [13]:
bmat*amat

3×3 Array{Float64,2}:
 5.55   9.75  13.95
 7.75  13.75  19.75
 9.05  16.25  23.45

and further

In [14]:
pi*amat

2×3 Array{Float64,2}:
 3.14159  6.28319   9.42478
 4.71239  7.85398  10.9956 

Here ```*``` denotes the conventional matrix multiplication. We can also have component-wise multiplication (e.g. the _Hadamard product_ of two matrices), which is denoted by ```.```, i.e.

In [15]:
[1.0 2.0; 2.0 3.0].*[1.5 1; 1.5 2]

2×2 Array{Float64,2}:
 1.5  2.0
 3.0  6.0

Addition is of, course, component-wise by default

In [16]:
[1.0 2.0; 2.0 3.0]+ones(2,2)

2×2 Array{Float64,2}:
 2.0  3.0
 3.0  4.0

## Mathematics and Floating Point Arithmetic

We can use _Julia_, especially in the _Jupyter_ environment as a calculator. _Julia_'s built-in mathematical functionality is powerful and flexible. By default functions are easily applied (component-wise) to vectors and matrices. For example,

In [18]:
sin.(pi*amat)

2×3 Array{Float64,2}:
  1.22465e-16  -2.44929e-16   3.67394e-16
 -1.0           1.0          -1.0        

Here we now have to deal with issues of numerical accuracy and the intricacies of floating-point arithmetic. The elements in the first row of the above matrix should all be equal to zero. For our purposes the difference between two floating points that can be represented is given by

In [19]:
eps(Float64)

2.220446049250313e-16

This is the next real number greater than ```1``` that can be represented. More generally we can use ```eps(x)``` to identify the next number greater than ```x``` that can be represented. E.g.

In [20]:
eps(0.0)

5.0e-324

In [21]:
eps(100.0)

1.4210854715202004e-14

So the density of floating point numbers that can be represented changes: it is densest around zero and then the spacing between adjacent representable floating point numbers increases exponentially. 

Floating point arithmetic can be a problem, and _Julia_ offers tools to deal with many of the issues that can arise, for example rounding:

In [22]:
round(4.1+0.7)

5.0

## Loops and Control Structures

Programming is meant to make repetetive tasks easier. *Loops* are one way of doing things repeatedly. 

For example, we can generate the *Monte Carlo estimate* of the integral
$$
\int_0^\pi \frac{\sin^2(x)}{1+x} 
$$

It is easy to check that the value of the integrand must be contained in the interval $[0,1]$. We can then generate a random number between $0$ and $\pi$, evaluate the integrand, and keep track of all trials for which this value is greater than that of another random variable $y\in[0,1]$.

In [40]:
N=100000 # Number of Monte Carlo trials
area = 0.0 # This will measure the number of simulated points that lie below the function.
for i in 1:N
    x=pi*rand()  # Generates a uniform random variable between 0 and Pi
    y=rand()     # Generates a uniform random variable between 0 and 1
    if (sin(x)*sin(x)/(1+x) > y) # Tests if y is less than the value of the function evaluated at x
        area = area +1.0 # if it is, it adds 1.0 to area.
    end
end
println(pi*area/N) # The fraction of number of trials which were below the line times Pi is the MC estimate for the integral.

0.6505295907788384


The result should be very close to the exact result, $0.6450$ (which can be evaluated using sine and cosine integrals).

Here we have a ```for``` loop running from 1 to $N$, which uses an ```if``` statement in the evaluation if the random point $y$ lies below the function, $f(x)$.

```for``` loops can run over every iteratable data type. For example,

In [44]:
for c in x3
    println(c)
end

f
o
u
r


In [48]:
xx=[x1,x2,x3,x4]
for xval in xx
    println(xval)
end

4
4.0
four
true


The type of ```xx``` is

In [49]:
typeof(xx)

Array{Any,1}

which is a very flexible construct, but which stretches *Julia*'s typing system and incurs performance penalties.

Again, ```types``` will concern us later again.

```for``` loops and ```if``` conditional statements already suffice to construct complex programs, and we will frequently use them below. By aed nd large, ```for``` loops are used when we do run over a set of iterators, without having the need to evaluate conditions with the aim of terminating the loop.

```if``` is much more flexible than suggested above, and can be extended very flexibly. We can use it together with the ```break``` command to terminate the loop.



In [55]:
rvec=rand(100)
lowthird=0
midthird=0
hghthird=0
for val in rvec
    if val<(1/3)
        lowthird+=1
    elseif val<(2/3)
        midthird+=1
    else
        hghthird+=1
    end
end
println(lowthird,",",midthird,", ",hghthird)

33,32, 35


Together with ```elseif``` (several in series if required) and ```else``` we can use ```if``` statements to implement several conditions and e.g. sort data into different categories.

But other constructs are available, which appe loop.ly conditions to the evaluation. This can either be at the start, or the end of a loop. ```while``` loops evaluate a condition at the start of the loop.

In [59]:
u=2
i=1
while u<4
    u+=1
    println(i,", ",u)
    i+=1
end
println(u)

1, 3
2, 4
4


Here the aim has been to give a basic overview of *Julia*'s ```type``` system, *Julia*'s used as a calculator for matrix manipulations, and basic control structures.

Next we will introduce
1. Some of *Julia*'s packages, and their general use.
2. Basic plotting.
3. Functions.
